modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory

[[mods]] #mandatory
modId="sync_effect_icons" #mandatory
logoFile=""
version="${version}" #mandatory
displayName="Sync Effect Icons" #mandatory
displayURL=""
authors="TelepathicGrunt"
credits="Special thanks to all the Forge tutorials and debugging help from other modders to help make this mod possible!"
description='''You know the icon you see in top right corner when you get an effect like Regeneration? This mod makes sure that icon stays visible instead of disappearing for a bit when teleporting between dimensions.'''